### PR TITLE
Update a user

### LINKED ISSUE #7: Update specific user information
# Issue
As a user, I want to update user information, so that I can keep my information up-to-date with my actions.
# Requirement
- [x] Create a controller to handle user PUT request
- [x] Connect controller to /user routes
- [x] Connect /user routes to API

### PR DESCRIPTION
**Pull request by verstraate**
# Issue
As a user, I want to update user information, so that I can keep my information up-to-date with my actions.
# Use
Given the nature of our game, players will need to make frequent decisions that will affect their information or maybe they just want to change their password. So, to achieve this, the player needs an easy way to access and update their user information in the database.
# Testing
There is, at the time of writing, currently a user in the database with...
```js
const user = {
  "id": "632eb9a2-c6ad-49a6-a882-b8bccca62105"
  "name": "ashures",
};
```
... as the necessary credentials.

Thanks!

### CODE REVIEW

**Review by otherotherjosh — COMMENTED** [review]
Nice work!! I've tested the update request via Postman and I can confirm it works as intended. Do you think it would be good to use `findFirst` instead of `findMany` which should return a single user instead of an array? It might be easier to read. You probably know more about this than me so let me know what your intention is. Other than that this is really easy to read, the comments definitely help!

**Comment by verstraate** [comment]
> Nice work!! I've tested the update request via Postman and I can confirm it works as intended. Do you think it would be good to use `findFirst` instead of `findMany` which should return a single user instead of an array? It might be easier to read. You probably know more about this than me so let me know what your intention is. Other than that this is really easier to read, the comments definitely help!

I didn't actually look into this! Could be worth implementing! Thanks for the recommendation.

**Comment by verstraate** [comment]
This works great, thanks for letting me know! I'll create an issue for a quick hotfix and replace the other `findMany` requests with `findFirst`!!

**Review by otherotherjosh — APPROVED** [review]
Tested it again, it still works. Thanks for the update!

**Pull request merged**
